name: Use Case
description: Describe and submit your use case for
title: "[UseCase]: "
labels: ["use-case"]
assignees: smoya
body:
  - type: markdown
    attributes:
      value: Share your use case(s) you expect to be considered during the development of the AsyncAPI Event Gateway.
  - type: textarea
    attributes:
      label: Please provide the name of your company and/or project.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please describe your project.
      description: Include details like what the project does, goals, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: We found the following challenges or difficulties...
      description: Provide as much detail as you can.
    validations:
      required: true
  - type: checkboxes
    id: severity
    attributes:
      label: Overall, we think this challenge/difficulty is...
      description: Please choose only one. 
      options:
        - label: A 'nice to have'.
        - label: A muct for us and decisive on using the Event Gateway.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Is there anything else you wish to share with us?


