name: Use Case
description: Describe and submit your use case for
title: "[UseCase]: "
labels: ["documentation"]
assignees: smoya
body:
  - type: markdown
    attributes:
      value: | 
        Thanks for taking the time to offer a use case!
  - type: textarea
    label: List or reviewers separated by commas.
    validations:
      required: true
  - type: textarea
    label: Our goals with this project are...
    description: Add you goal(s) in this text area.
    validations:
      required: true
  - type: textarea
    label: We expect to...
    description: Add any and all expectations in this text area.
    validations:
      required: true
  - type: textarea
    label: We found the following challenges or difficulties...
    description: Provide as much detail as you can.
    validations:
      required: true
  - type: checkboxes
    id: severity
    attributes:
      label: Overall, we think this challenge/difficulty is...
      description: Please choose only one. 
      options:
        - label: A 'nice to have'.
        - label: A muct for us and decisive on using the Event Gateway.
      validations:
        required: true
  - type: textarea
    label: Is there anything else you wish to share with us?


